---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pengzhisheng.
--- DateTime: 2022/8/24
---
print("hello world")

sum = 0
num = 1
while num <= 100 do
    sum = sum + num
    num = num + 1
end

print("sum =", sum)

